"""Recreated migration file

Revision ID: 575dbc639854
Revises: c663653f6487
Create Date: 2024-11-29 15:14:35.014445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575dbc639854'
down_revision: Union[str, None] = 'c663653f6487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(), nullable=False))
    op.drop_column('product', 'iid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('iid', sa.INTEGER(), nullable=False))
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
